version: "3"
services:
  #PHP Service
  api:
    build:
      context: ./api
    container_name: api
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
    volumes:
      - ./api:/var/www/laravel
    networks:
      - app-network
    depends_on:
      - db

  #Background Worker Service
  worker:
    build:
      context: ./api
    container_name: worker
    restart: unless-stopped
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      CONTAINER_ROLE: queue
    volumes:
      - ./api:/var/www/laravel
    networks:
      - app-network
    depends_on:
      - db
      - api

  #NextJS Service
  client:
    build:
      context: ./client
      target: runner
    container_name: client
    volumes:
      - ./client:/app
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - app-network
    depends_on:
      - api

  #Nginx Service
  # webserver:
  #   image: nginx:1.21
  #   container_name: webserver
  #   restart: unless-stopped
  #   tty: true
  #   links:
  #     - api
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./api/:/var/www
  #     - ./api/nginx/conf.d/:/etc/nginx/conf.d/
  #   networks:
  #     - app-network

  #MySQL Service
  db:
    image: mysql:5
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: portfolio
    volumes:
      - dbdata:/var/lib/mysql/
      - ./api/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
