name: Prebuild Check

on: "push"

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: cd client && yarn
      - run: cd client && yarn type
      - run: cd client && yarn lint
