name: Prebuild Check

on: "push"

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: cd client && yarn
      - run: cd client && yarn type
      - run: cd client && yarn lint
  build-be:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1.1"
      - uses: actions/checkout@v3
      - name: Load ENV
        run: cd api && php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Update Dependencies
        run: cd api && composer update && composer dump-autoload
      - name: Install Dependencies
        run: cd api && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Composer Generate Key
        run: cd api && php artisan key:generate
      - name: Migrate DB
        run: cd api && php artisan migrate
      - name: Seed DB
        run: cd api && php artisan db:seed
      - name: Run Code Checker
        run: cd api && ./vendor/bin/php-cs-fixer fix ./app ./config ./database ./routes ./tests --config=./.php-cs-fixer.php --diff --dry-run --using-cache=no
      - name: Execute tests (Unit and Feature tests) via PHPUnits
        run: cd api && php artisan optimize:clear && php artisan test --coverage-clover ./report.xml --coverage-html=coverage
